name = "fabric_1.21.4_bfe"
author = "amtea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a40a6311e29885cd7c31310d518c681f0553984fef9d378f0a1664ec6ca29d9f"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
