name = "fabric_1.21.4_bfe"
author = "amtea"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24440dfd4156dfc7b0a401a84062a4c878a3534c000d936d2b54e19a7f755a27"

[versions]
fabric = "0.17.2"
minecraft = "1.21.4"
